### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by JerryCjr** [JerryCjr/jerrycjr.github.io#34]
- [x] border
- [x] 垂直居中的实现方式
- [x] 选择器有哪些
- [ ] position 属性的理解
- [ ] box-sizing

## border

1. 利用 border 实现一个三角形

### 利用 border 实现一个三角形

```css
.triangle {
  width: 0;
  height: 0;
  border-top: 10px solid  green;
  border-left: 10px solid transpaprent;
  border-right: 10px solid transparent;
  border-bottom: 10px solid transparent;
}
```

> 一句话阐述

宽高全为 0, 靠 border 撑开 (理解 border: border-width, 第一个属性是边框的宽度)

上下左右都是 10px, content 宽高为 0, 形成的是一个正方形, 20px * 20px
只给 top 颜色, 其余都是 transparent, 形成的是上三角, 尖儿朝下, 底为 10, 高为 10

![image](https://user-images.githubusercontent.com/35129098/115850901-f508bd00-a458-11eb-9a77-0d4cf7eaa5e1.png)

### 利用 border 实现三角形, 要求实现一个左直三角形

![image](https://user-images.githubusercontent.com/35129098/115852634-e02d2900-a45a-11eb-9237-2ab9272b68a9.png)

> 一句话阐述

看图, 上面的图是 border 都有颜色的时候
要想得到左直三角形, 就是 top 和 left 都有颜色, 组合一下

## 垂直居中的实现方式

> body 是父元素, div 是子元素

1. flex
2. position + transform
3. position + margin

### flex

```css
body {
  display: flex;
  align-items; // 纵轴居中
}
```

```css
body {
  display: flex;
  flex-direction: column;  // 改变默认的主轴排列, 变为竖着排列
  justify-content: center; // 
}
```

### position

```css
body {
  position: relative;
}

div {
  position: absolute;
  top: 50%;
  transform: translate(0, -50%);

  width ...
  height ...
}
```

> 一句话阐述

top: 距离顶 50%, 但是这个时候中心点不在 50%的地方, 中心点比 50%的地方多了高度的 50%
transform: translate(0, -50%): 在 y 轴方向, 以中心点为基点, 移动高度的 -50%, 即向上移动了高度的 50%;

### position + margin

```css
body {
  position: relative;
}

div {
  position: absolute;
  top: 0;
  bottom: 0;
  margin: auto 0;

  width ...
  height ...
}
```

> 一句话阐述 

没什么好阐述的 经常用

## css 选择器

id 选择器
class 选择器

标签选择器
```css
  p {}
```

分组选择器
```css
  p, div, span {}
```

后代选择器
```css
  div ul li {}
```

属性选择器
```css
  [name = 'part'] {}
```

通用选择器
```css
  * {}
```

兄弟选择器
```css
  div+p {}
```

直接父子选择器
```css
  div>p {}
```

## position

1. static
2. relative
3. absolute
4. fixed
5. sticky

> static

默认值, 指定元素使用正常的布局行为, 即元素在文档常规流中当前的布局位置

> relative

1. **文档流:** - 不改变文档流,元素先放置在未添加定位时的位置, 再在不改变页面布局的前提下调整元素位置 
(因此会在该元素原先的位置留下空白)

> absolute

1. **文档流:** 元素会被移出正常的文档流, 并不为元素预留空间
2. **元素的位置:** 通过指定元素相对于最近的非 static 定位祖先元素的偏移, 来确定元素的位置.

tips:

元素的位置:  
通过指定元素相对于最近的非 static 定位祖先元素的偏移, 来确定元素的位置
当这样的祖先元素不存在时，则相对于ICB（inital container block, 初始包含块）

> fixed

1. **文档流:** 元素会被移出正常的文档流, 并不为元素预留空间
2. **元素的位置:** 通过指定元素相对于屏幕视口(view port) 的位置来指定元素位置.
3. **滚动:** 元素的位置在屏幕滚动时不会改变. 
4. **打印:** 打印时, 元素会出现在每页的固定位置
5. **层叠上下文**: fixed 属性会创建新的层叠上下文 (z-index: 指定)

> sticky

1. **文档流:** 根据正常文档流进行定位
2. **元素的位置:** 相对于它的最近滚动祖先(nearest scrolling ancestor) 和 container block (最近块级祖先 nearest block-level ancestor), 基于 left, right, top, bottom的值进行偏移. **偏移值不会影响其他元素的位置**
3. **层叠上下文:** 该值总会创建一个新的层叠上下文

可以理解为相对定位和固定定位的混合, 元素在跨越特定阈值前为相对定位，之后为固定定位

```css
#one { position: sticky; top: 10px; }
```

解释: 

在 viewport 视口滚动到元素 top 距离小于 10px 之前, 元素为相对定位 -- 和 relatvie 是一样的,
之后, 元素将固定与顶部距离 10px 的地方, -- 这个时候又和 fixed 一样
viewport 滚动回阈值以下的时候还会恢复到 relatvie

## box-sizing

```css
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

```

box-sizing: content-box;  // 是默认值, 表示设置的宽就是 content 的宽, 不包含border 和 padding 的宽
box-sizing: border-box; // 告诉浏览器, 设置的宽是整体的宽 = content 的宽 + border 的宽 + padding 的宽
