### ISSUE TITLE
BFC

### ISSUE THREAD

**Issue by JerryCjr** [JerryCjr/jerrycjr.github.io#55]
q:

常规流?定位流?浮动流?什么意思?区别是什么?
什么是 BFC?
如何创建一个 BFC?
BFC 带来了哪些影响?

## 常规流?定位流?浮动流?什么意思?区别是什么?

> 常规流

常规的流式布局, 元素按照顺序排列

> 浮动流

使用 float 做浮动定位 float: left / right
none 为默认值, 表示不使用浮动定位

浮动流会脱离常规文档流, 不会保留原始位置, 
**别的元素会忽视这个元素进行排列**, 
但是别的元素的**文字不会忽略浮动元素, 会形成环绕的效果**

> 定位流

使用 position 做定位, position:  absolute / fixed / sticky
static 为默认值, 表示不使用定位

定位流会脱离常规文档流, 不会保留原始位置,
**别的元素会忽略这个元素进行排列, 文字也会忽略**, 
所以定位流原始的位置会被后来的元素顶替, 定位流遮盖到常规文档流上方

## 什么是 BFC

BFC = Block Formatting Context
FC = Formatting Context 

理解 BFC 先理解 FC

### FC

FC 直译过来是格式上下文
它是页面的一块渲染区域, 有一套渲染规则, 决定了其子元素如何布局, 以及和其他元素之间的关系和作用
理解上相当于是一个隔离容器, 容器内遵循一套规则排列, 而且容器内不管怎么排列都不会影响到外部

这里没有具体说是哪种元素, 这里的元素实际有两类, 一类是块级盒子, 一类是内联盒子
如果是块级盒子, 这里的 FC 指的就是 BFC
如果是内联盒子, 这里的 FC 指的就是 IFC

### BFC

概念理解清楚了, 这里讲一下, BFC 有哪些**渲染规则, 即它对里面渲染的块级元素有什么要求?**

1. 在一个块格式区域中, 盒子会从包含块的顶部开始, 按序垂直排列. 同级盒子的垂直距离由"margin"属性决定. 相邻两个块级盒子间的垂直间距会遵循外边距折叠原则被折叠
2. 在一个块格式区域中,每个盒子的左边缘会和包含块的左边缘重合(根据排版顺序会有区别, 从左到右排版就是和左边缘重合, 从右到左排版就是和右边缘重合)

### IFC

在内联格式区域中, 盒子会从包含块的顶部开始, 按序水平排列. 只有水平外边距, 边框和内边距会被保留. 这些盒子可以以不同的方式在垂直方向上对齐, 可以底部对齐或者顶部对齐, 或者按照文字底部对齐.我们把包含一串盒子的矩形区域称为一个line box.

## 如何创建一个 BFC

1. 根元素 (<html></html>)
2. 浮动元素 (float 不是 none)
3. 绝对定位元素 (position 不是 static 和 relative)
4. 行内块级元素 (display: inline-block)
5. overflow (overflow 不是 visible 默认值的时候, 比如 auto, hidden, scroll 都可以创建一个 BFC)
6. display: flow-root
7. 弹性元素(display: flex)
8. 网格元素(display: grid)

## BFC 带来了哪些影响

1. 外边距折叠
2. 浮动

浮动定位和清除浮动时只会应用于同一个BFC内的元素。
浮动不会影响其它BFC中元素的布局，而清除浮动只能清除同一BFC中在它前面的元素的浮动

### 外边距折叠

q:

1. 相邻兄弟元素 外边距重叠
2. 父子元素 外边距重叠

#### 一句话阐述

在规范中提到，块级元素之间的外边距会发生折叠。这意味着，如果一个具有上边距的元素排在在一个具有下边距的元素之下时，他们之间的间距不会是这两个外边距的和，即外边距会发生折叠，简单来说就是，间距与两个外边距中的较大者一样大。

#### 相邻兄弟元素 外边距重叠

```html
  <body>
    <div class="blue"></div>
    <div class="red"></div>
  </body>
```

```css
.blue,
.red {
  width: 100%;
  height: 100px;
}

.blue {
  background-color: blue;
  margin-bottom: 50px;
}

.red {
  margin-top: 200px;
  background-color: red;
}
```

这是同一个 BFC 中的两个相邻的兄弟元素, 边距发生重叠
预期想要有 250px 的边距, 但是现在重叠后只会取最大值, 即 200px

##### 解决方法

> 方法 1, 中间放一个高度为 0.1px, 且设置了 margin 的 div

其实相当于中间有一个无关紧要的元素隔开了我们比较 care 的两个块级元素.

> 方法 2, 给元素添加定位或者浮动

这样的影响不是很好, 会改变页面的布局, 浮动和定位也会带来别的问题

```css
.red {
  position: absolute;
  // float: left;
}
```

> 方法 3, 给另一个元素添加一个父元素

**要保证父元素是另一个 BFC**, 否则在同一个 BFC 中也会有边距重叠的问题

方式有很多, 比如:
1. 可以使用 overflow
2. 可以使用 display: flow-root

```html
<div class="blue"></div>
  <div class="container">
  <div class='red'></div>
</div>
```

```css
// 父元素
.container {
  overflow:  hidden; // 使用 overflow: hidden 变为一个独立的 BFC
  // display: flow-root; // 使用 display: flow-root 变成一个无副作用的独立的 BFC
}
```

#### 父子元素 margin 重叠问题

![image](https://user-images.githubusercontent.com/35129098/116716781-bc458680-aa0a-11eb-8327-ca5a7519921b.png)

##### 代码

```html
  <body>
    <div class="container">
      <div class="red"></div>
    </div>
  </body>
```

```css
.container {
  background-color: yellow;
}

.red {
  width: 100%;
  height: 100px;
  margin: 100px 20px;
  background-color: red;
}

```

##### 分析

父子元素在同一个 BFC 中, container 为父, red 为子, red 上下有个 100px 的 margin
但是可以看得出来上下的边距并没有生效

##### 解决

> 方法 1, 将父元素变成独立的 BFC

1. display: flow-root; 
2. overflow: hidden;

```css
.container {
  /* overflow: hidden; */
  display: flow-root;
  background-color: yellow;
}
```

效果:

![image](https://user-images.githubusercontent.com/35129098/116717159-2eb66680-aa0b-11eb-81a4-acde681dc114.png)

> 方法 2: 使父元素和子元素隔开

1. border: 1px solid red;
2. padding: 0.1px;

```css
.container {
  /* overflow: hidden; */
  /* display: flow-root; */
  border: 1px solid green;
  /* padding: 0.1px; */
  background-color: yellow;
}
```
效果

![image](https://user-images.githubusercontent.com/35129098/116717851-eea3b380-aa0b-11eb-84c8-3f9885d6aba1.png)

#### 消除浮动元素的影响, 实现两栏自适应布局

![image](https://user-images.githubusercontent.com/35129098/116719650-e64c7800-aa0d-11eb-8549-e7f75fa2d40f.png)

```html
  <body>
    <div class="container">
      <div class="box1">浮动浮动浮动浮动浮动浮动浮动浮动浮动</div>
      <div class="box2">
        我是一段文字的内容, 我没有浮动,我是一段文字的内容,
        我没有浮动,我是一段文字的内容, 我没有浮动
      </div>
    </div>
  </body>
```

```css
.container {
  width: 100px;
}

.box1 {
  width: 50px;
  float: left;
  background-color: pink;
}

.box2 {
  background-color: green;
}
```

阐述: 

这种情况下, box1 是浮动元素, box2 是非浮动元素
如果 box2 文字少的情况下, 是并列排列的结果
如果 box2 文字多的情况下, 是环绕的结果
**这是因为 box2 中的内容受到了外部 box1 浮动元素的影响, 其实 box2 有一部分已经被 box1 遮挡了, 只是文字没有遮挡**

box1 是一个独立的 BFC, box2 和 container 属于同一个 BFC

更改:

当我们将 box2 更改为一个新的 BFC, 来消除浮动元素的影响, 使两列可以并列显示, 不会产生环绕效果, 如下

![image](https://user-images.githubusercontent.com/35129098/116720201-7e4a6180-aa0e-11eb-9824-74a094f07c7a.png)

```css
.box2 {
  /* display: flow-root; */
  overflow: auto;
  background-color: green;
}
```

当文字大小改变, 或者左边浮动元素的宽度改变
box2 始终会自适应宽度, **实现了两栏自适应布局**

#### 解决包含浮动元素的父元素高度塌陷的问题

![image](https://user-images.githubusercontent.com/35129098/116721290-b9996000-aa0f-11eb-9c88-209122d0a818.png)

```html
  <body>
    <div class="container">
      <div class="box1">box1</div>
      <div class="box2">box2</div>
    </div>
  </body>
```

```css
.container {
  background-color: hotpink;
  border: 1px solid hotpink;
}

.box1,
.box2 {
  float: left;
  width: 100px;
  height: 100px;
}

.box1 {
  background-color: cyan;
}

.box2 {
  background-color: greenyellow;
}
```

阐述: 

这是一个常规的浮动场景, 
父元素 container  有两个子元素 box1, box2, 这两个子元素都是浮动元素
父元素高度产生塌陷, 无法包住这俩, 从图上看就是没有高度

更改:

使父元素变成一个新的 BFC, 效果如下:

![image](https://user-images.githubusercontent.com/35129098/116721761-46dcb480-aa10-11eb-91a8-04d2327ca15b.png)

```css
.container {
  background-color: hotpink;
  border: 1px solid hotpink;
  /* overflow: hidden; */
  display: flow-root;
}
```

---

参考链接
[MDN BFC](https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Block_formatting_context)
[MDC 常规流中的块级和内联布局](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Flow_Layout/Block_and_Inline_Layout_in_Normal_Flow)
[10 分钟了解 BFC](https://zhuanlan.zhihu.com/p/25321647)
